// <auto-generated />
namespace SuperMarketApplication.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddAddressToSuperMarket : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAddressToSuperMarket));
        
        string IMigrationMetadata.Id
        {
            get { return "201408041700375_AddAddressToSuperMarket"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
